title: Black Radish - Documentation
description: Black Radish - Automated Testing Framework
remote_theme: carlosperate/jekyll-theme-rtd

site_author: Dmitry Mamontov
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist